.TH FORGE "1" "November 2010" "" "User Commands"

.SH NAME
forge \- simple file creation via templates

.SH SYNOPSIS
.B forge
[\fITEMPLATE\fR] \fIFILE\fR
.br
.B forge
\fILONG-OPTION\fR

.SH DESCRIPTION
.\" Add any additional description here
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit

.SH TEMPLATE FILES
Template files are parsed and used when creating a new file

.SS "Template Functions"
.TP
.B ((dir))
Will be replaced with the directory of the file to be created
.br
ex: '/home/batman/filename.txt' → '/home/batman/'

.TP
.B ((file))
Will be replaced with the filename of the file to be created
.br
ex: '/home/batman/filename.txt' → 'filename.txt'

.TP
.B ((base))
Will be replaced with the filename base of the file to be created
.br
ex: '/home/batman/filename.txt' → 'filename'

.TP
.B ((ext))
Will be replaced with the filename extention of the file to be created
.br
ex: '/home/batman/filename.txt' → 'txt'

.TP
.B ((date[,arg]))
Will be replaced with the current date, formated by arg. If arg is not given, '%Y-%m-%d' is used
.br
ex: ((date)) → '2010-11-29'
.br
ex: ((date,%m-%d-%Y)) → '11-29-2010'

.TP
.B ((time[,arg]))
Will be replaced with the current time, formated by arg. If arg is not given, '%H:%M:%S' is used
.br
ex: ((time)) → '13:48:53'
.br
ex: ((time,%I:%M:%S %p)) → '01:48:53 PM'

.TP
.B ((user))
Will be replaced with the username of the current uses
.br
ex: ((user)) → 'batman'

.TP
.B ((host))
Will be replaced with the hostname of the current machine
.br
ex: ((host)) → 'batcomputer'

.TP
.B ((sys,arg))
Will be replaced with the STDOUT & STDERR output generated by running arg
.br
ex: ((sys,uname -o)) → 'GNU/Linux'

.TP
.B ((ret,arg))
Will be replaced with the return value generated by running arg
.br
ex: ((ret,cat /bin/ls)) → '0'
.br
ex: ((ret,cat /bin/junk)) → '256'

.TP
.B ((repl,arg))
Will be replace with the value of arg, with all macros expanded (see Template Macros)
.br
ex: ((repl,Welcome to the [[host]], [[user]].)) → 'Welcome to the batcomputer, batman.'

.TP
.B ((echo,arg))
Will be replaced with the value of arg, with no macros expanded (see Template Macros)
.br
ex: ((repl,Welcome to the [[host]], [[user]].)) → 'Welcome to the [[host]], [[user]].'




.SS "Template Macros"

.TP
.B [[dir]]
Identical to ((dir))

.TP
.B [[file]]
Identical to ((file))

.TP
.B [[base]]
Identical to ((base))

.TP
.B [[ext]]
Identical to ((ext))

.TP
.B [[date]]
Identical to ((date))

.TP
.B [[time]]
Identical to ((time))

.TP
.B [[user]]
Identical to ((user))

.TP
.B [[host]]
Identical to ((host))

.TP
.B [[dfo]]
Will be replaced with the delimeter used for opening a function
.br
ex: ((repl,[[dfo]])) → '(('

.TP
.B [[dfc]]
Will be replaced with the delimeter used for closing a function
.br
ex: ((repl,[[dfc]])) → '))'

.TP
.B [[dmo]]
Will be replaced with the delimeter used for opening a macro
.br
ex: ((repl,[[dmo]])) → '[['

.TP
.B [[dmc]]
Will be replaced with the delimeter used for closing a macro
.br
ex: ((repl,[[dmc]])) → ']]'




.SH AUTHOR
Written by Josh Komoroske.
.br
forge source code repository: <http://github.com/sigint/forge>

.SH COPYRIGHT
Copyright \(co 2010 Josh Komoroske
.br
License BSD:
.br
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL JOSHUA KOMOROSKE BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

